
javascripts:
  backbone:
    - underscore.js
    - haml.js
    - backbone.js
  metric_model:
    - models/metric.js
    
templates:
  metric_view:
    - app/views/metrics/*.jst.haml
    
metric_view:
  - app/views/**/*.jst.haml
